Repository OskarStark/doctor-rst, pull requests merged in 2020-11, with the labels that each got.

#811 Enhancement: New rule string_replacement
  docs/rules.md
  src/Rule/AmericanEnglish.php
  src/Rule/BeKindToNewcomers.php
  src/Rule/CheckListRule.php
  src/Rule/ReplaceCodeBlockTypes.php
  src/Rule/Replacement.php
  src/Rule/StringReplacement.php
  src/Rule/Typo.php
  tests/Rule/StringReplacementTest.php
Labels: New rule

#813 only one max blank lines violation
  src/Analyzer/RstAnalyzer.php
  src/Rule/MaxBlankLines.php
  src/Value/Line.php
  src/Value/Lines.php
  tests/Analyzer/RstAnalyzerTest.php
  tests/Fixtures/max_blanklines.rst
Labels: enhancement

#816 Enhancement: New rule no_directive_after_default_directive
  docs/rules.md
  src/Rule/NoDirectiveAfterDefaultDirective.php
  tests/Rule/NoDirectiveAfterDefaultDirectiveTest.php
Labels: New rule

#817 Enhancement: New rule ensure_exactly_one_space_between_link_definition_and_link
  docs/rules.md
  src/Rule/EnsureExactlyOneSpaceBetweenLinkDefinitionAndLink.php
  tests/Rule/EnsureExactlyOneSpaceBetweenLinkDefinitionAndLinkTest.php
Labels: New rule

#818 Enhancement: Support for codeimport directive
  src/Rst/RstParser.php
  src/Rule/BlankLineAfterDirective.php
Labels: enhancement

#828 Enhancement: Add workflow for generating the docs
  .github/workflows/documentation.yaml
  docs/rules.md
  src/Command/RulesCommand.php
Labels: GithubActions, enhancement

#830 Enhancement: Use PHPStan max level
  phpstan.neon.dist
  src/Rule/CheckListRule.php
Labels: enhancement

#831 Enhancement: Analyse "tests" directory with PHPStan
  .github/workflows/ci.yaml
  .php_cs.dist
  config/cache.php
  config/services.php
  phpstan.neon.dist
  tests/Analyzer/MemoizingAnalyzerTest.php
  tests/Fixtures/Rule/Dummy.php
  tests/Helper/PhpHelperTest.php
  tests/Helper/XmlHelperTest.php
  tests/Helper/YamlHelperTest.php
  tests/Rst/RstParserTest.php
  tests/Rst/Value/LinkUsageTest.php
  tests/Rule/AvoidRepetetiveWordsTest.php
  tests/Rule/DeprecatedDirectiveMajorVersionTest.php
  tests/Rule/DeprecatedDirectiveMinVersionTest.php
  tests/Rule/EvenBracketsCountTest.php
  tests/Rule/ExtendAbstractAdminTest.php
  tests/Rule/ExtendAbstractControllerTest.php
  tests/Rule/ExtendControllerTest.php
  tests/Rule/ExtensionXlfInsteadOfXliffTest.php
  tests/Rule/FinalAdminClassesTest.php
  tests/Rule/FinalAdminExtensionClassesTest.php
  tests/Rule/IndentionTest.php
  tests/Rule/KernelInsteadOfAppKernelTest.php
  tests/Rule/LineLengthTest.php
  tests/Rule/MaxBlankLinesTest.php
  tests/Rule/NoAdminYamlTest.php
  tests/Rule/NoBashPromptTest.php
  tests/Rule/NoBlankLineAfterFilepathInCodeBlockTest.php
  tests/Rule/NoBlankLineAfterFilepathInTwigCodeBlockTest.php
  tests/Rule/NoBlankLineAfterFilepathInYamlCodeBlockTest.php
  tests/Rule/NoComposerReqTest.php
  tests/Rule/NoExplicitUseOfCodeBlockPhpTest.php
  tests/Rule/NoPhpPrefixBeforeBinConsoleTest.php
  tests/Rule/NoPhpPrefixBeforeComposerTest.php
  tests/Rule/NoSpaceBeforeSelfXmlClosingTagTest.php
  tests/Rule/PhpPrefixBeforeBinConsoleTest.php
  tests/Rule/ReplacementTest.php
  tests/Rule/ShortArraySyntaxTest.php
  tests/Rule/SpaceBeforeSelfXmlClosingTagTest.php
  tests/Rule/StringReplacementTest.php
  tests/Rule/TypoTest.php
  tests/Rule/UseDeprecatedDirectiveInsteadOfVersionaddedTest.php
  tests/Rule/ValidUseStatementsTests.php
  tests/Rule/VersionaddedDirectiveMajorVersionTest.php
  tests/Rule/VersionaddedDirectiveMinVersionTest.php
  tests/Rule/VersionaddedDirectiveShouldHaveVersionTest.php
  tests/Rule/YamlInsteadOfYmlSuffixTest.php
  tests/Rule/YarnDevOptionAtTheEndTest.php
  tests/Rule/YarnDevOptionNotAtTheEndTest.php
  tests/Traits/DirectiveTraitTest.php
  tests/Traits/ListTraitTest.php
  tests/Util/DirectiveTraitWrapper.php
  tests/Util/ListItemTraitWrapper.php
  tests/Value/RuleGroupTest.php
Labels: enhancement

#834 Enhancement: Remove complex and not working rule
  docs/rules.md
  src/Rule/EvenBracketsCount.php
  tests/Rule/EvenBracketsCountTest.php
Labels: enhancement

#836 Fix: Return type
  src/Rule/CheckListRule.php
  tests/Rule/AmericanEnglishTest.php
  tests/Rule/ReplacementTest.php
  tests/Rule/StringReplacementTest.php
  tests/Rule/TypoTest.php
Labels: bug

#838 Enhancement: Simplify analyzer
  src/Analyzer/RstAnalyzer.php
Labels: enhancement

#840 Enhancement: Use symfony/string for string cleanup
  src/Rst/RstParser.php
  src/Value/Line.php
Labels: enhancement
