Repository OskarStark/doctor-rst, pull requests merged in 2020-10, with the labels that each got.

#758 Enhancement: Support code-block:: php-attributes
  src/Rst/RstParser.php
  src/Rule/BlankLineAfterFilepathInPhpCodeBlock.php
  src/Rule/EnsureOrderOfCodeBlocksInConfigurationBlock.php
  src/Rule/Indention.php
  src/Rule/LowercaseAsInUseStatements.php
  src/Rule/NoBlankLineAfterFilepathInPhpCodeBlock.php
  src/Rule/NoInheritdocInCodeExamples.php
  src/Rule/NoNamespaceAfterUseStatements.php
  src/Rule/NoPhpOpenTagInCodeBlockPhpDirective.php
  src/Rule/OrderedUseStatements.php
  src/Rule/PhpOpenTagInCodeBlockPhpDirective.php
  tests/Rst/RstParserTest.php
  tests/Rule/BlankLineAfterFilepathInPhpCodeBlockTest.php
  tests/Rule/EnsureOrderOfCodeBlocksInConfigurationBlockTest.php
  tests/Rule/LowercaseAsInUseStatementTest.php
  tests/Rule/NoBlankLineAfterFilepathInPhpCodeBlockTest.php
  tests/Rule/NoInheritdocInCodeExamplesTest.php
  tests/Rule/NoNamespaceAfterUseStatementsTest.php
  tests/Rule/OrderedUseStatementsTest.php
Labels: enhancement

#761 Enhancement: Use php-attributes at second
  src/Rule/EnsureOrderOfCodeBlocksInConfigurationBlock.php
  tests/Rule/EnsureOrderOfCodeBlocksInConfigurationBlockTest.php
Labels: enhancement

#770 Enhancement: Rename (A|a)nalyser to (A|a)nalyzer
  .github/workflows/build.yaml
  config/cache.yaml
  config/services.yaml
  entrypoint.sh
  src/Analyzer/Analyzer.php
  src/Analyzer/Cache.php
  src/Analyzer/FileCache.php
  src/Analyzer/InMemoryCache.php
  src/Analyzer/MemoizingAnalyzer.php
  src/Analyzer/RstAnalyzer.php
  src/Application.php
  src/Command/AnalyzeCommand.php
  src/Formatter/ConsoleFormatter.php
  src/Formatter/Formatter.php
  src/Formatter/GithubFormatter.php
  src/Value/AnalyzerResult.php
  tests/Analyzer/FileCacheTest.php
  tests/Analyzer/MemoizingAnalyzerTest.php
  tests/Formatter/ConsoleFormatterTest.php
  tests/Formatter/GithubFormatterTest.php
Labels: enhancement

#771 fix excluded violations
  src/Value/ExcludedViolationList.php
  tests/Value/ExcludedViolationListTest.php
Labels: bug

#774 Enhancement: New rule - NoBracketsInMethodDirective
  docs/rules.md
  src/Rule/NoBracketsInMethodDirective.php
  tests/Rule/NoBracketsInMethodDirectiveTest.php
Labels: enhancement

#775 Enhancement: New rule - SpaceBetweenLabelAndLinkInRef
  docs/rules.md
  src/Rule/SpaceBetweenLabelAndLinkInRef.php
  tests/Rule/SpaceBetweenLabelAndLinkInRefTest.php
Labels: enhancement

#776 Enhancement: Upgrade Humbug box to 3.8.5
  .github/workflows/build.yaml
Labels: enhancement

#778 Automatically enable GitHub error formatter in a GitHub actions environment
  composer.json
  composer.lock
  src/Command/AnalyzeCommand.php
Labels: enhancement

#780 Enhancement: Use dedicated exception class
  src/Formatter/Exception/FormatterNotFound.php
  src/Formatter/Registry.php
  tests/Formatter/RegistryTest.php
Labels: enhancement

#785 Enhancement: Refactor test to use yield
  tests/Rule/NoExplicitUseOfCodeBlockPhpTest.php
Labels: enhancement

#786 Enhancement: Allow ..code-block:: php after specific directives
  src/Rule/NoExplicitUseOfCodeBlockPhp.php
  tests/Rule/NoExplicitUseOfCodeBlockPhpTest.php
Labels: bug

#787 Enhancement: New rule OnlyBackslashesInNamespacesInPhpCodeBlock
  docs/rules.md
  src/Rule/OnlyBackslashesInNamespaceInPhpCodeBlock.php
  tests/Rule/OnlyBackslashesInNamespacesInPhpCodeBlockTest.php
Labels: New rule

#788 Enhancement: Add shortcut to check if in PHP code-block
  src/Rule/NoInheritdocInCodeExamples.php
  src/Rule/OnlyBackslashesInNamespaceInPhpCodeBlock.php
  src/Traits/DirectiveTrait.php
Labels: enhancement

#790 Enhancement: New rule OnlyBackslashesInUseStatementsInPhpCodeBlock
  docs/rules.md
  src/Rule/OnlyBackslashesInUseStatementsInPhpCodeBlock.php
  tests/Rule/OnlyBackslashesInUseStatementsInPhpCodeBlockTest.php
Labels: New rule

#791 Fix: Stricter checks
  src/Rule/OnlyBackslashesInNamespaceInPhpCodeBlock.php
  src/Rule/OnlyBackslashesInUseStatementsInPhpCodeBlock.php
Labels: bug
