Repository OskarStark/doctor-rst, pull requests merged in 2023-01, with the labels that each got.

#1231 New rule: Ensure exactly one space before directive type
  docs/rules.md
  src/Rule/EnsureExactlyOneSpaceBeforeDirectiveType.php
  tests/Rule/EnsureExactlyOneSpaceBeforeDirectiveTypeTest.php
Labels: New rule 🎁

#1240 NoExplicitUseOfCodeBlockPhp can have image has previous directive or terminal code block
  src/Rule/NoExplicitUseOfCodeBlockPhp.php
  tests/Rule/NoExplicitUseOfCodeBlockPhpTest.php
Labels: bug

#1244 No contraction missing cases
  src/Rule/NoContraction.php
  tests/Rule/NoContractionTest.php
Labels: enhancement

#824 Enhancement: New Rule for checking filenames and new type FILE_INFO
  docs/rules.md
  dummy/.doctor-rst.yaml
  dummy/docs/index.rst
  dummy/docs/tutorial/introduction_one.rst
  src/Analyzer/RstAnalyzer.php
  src/Rule/FileInfoRule.php
  src/Rule/FilenameUsesDashesOnly.php
  src/Rule/FilenameUsesUnderscoresOnly.php
  tests/Formatter/ConsoleFormatterTest.php
  tests/Rule/FilenameUsesDashesOnlyTest.php
  tests/Rule/FilenameUsesUnderscoresOnlyTest.php
Labels: New rule 🎁

#1255 Add report of unused whitelist rules
  phpstan-baseline.neon
  src/Command/AnalyzeCommand.php
  src/Formatter/ConsoleFormatter.php
  src/Value/AnalyzerResult.php
  src/Value/ExcludedViolationList.php
  tests/Formatter/ConsoleFormatterTest.php
  tests/Formatter/GithubFormatterTest.php
  tests/Value/AnalyzerResultTest.php
  tests/Value/ExcludedViolationListTest.php
Labels: enhancement

#1272 Fix order in `EnsureOrderOfCodeBlocksInConfigurationBlock`
  src/Rule/EnsureOrderOfCodeBlocksInConfigurationBlock.php
  tests/Rule/EnsureOrderOfCodeBlocksInConfigurationBlockTest.php
Labels: bug
