Repository OskarStark/doctor-rst, pull requests merged in 2023-05, with the labels that each got.

#1388 Add `RemoveTrailingWhitespace` rule
  docs/rules.md
  src/Rule/RemoveTrailingWhitespace.php
  tests/Rule/RemoveTrailingWhitespaceTest.php
Labels: New rule 🎁

#1404 Reduce IO in RstAnalyzer
  src/Analyzer/RstAnalyzer.php
Labels: Performance

#1405 Prevent excessive use of `preg_match()`
  src/Helper/PhpHelper.php
Labels: Performance

#1408 `RstParser->isFootnote()`: Prevent excessive use of `preg_match()`
  src/Rst/RstParser.php
Labels: Performance

#1407 Perf optimize `Line::isDefaultDirective()`
  src/Value/Line.php
Labels: Performance

#1413 Move method call out of hot loop
  src/Analyzer/RstAnalyzer.php
Labels: Performance

#1412 Perf optimize `Line::isDirective()`
  src/Value/Line.php
Labels: Performance

#1414 Fixed matching directives ending in newline
  src/Value/Line.php
  tests/Rst/Value/LineTest.php
Labels: bug
