Repository OskarStark/doctor-rst, pull requests merged in 2023-03, with the labels that each got.

#1337 New Rule `TitleUnderlineLengthMustMatchTitleLength`
  src/Rule/TitleUnderlineLengthMustMatchTitleLength.php
  tests/Rule/TitleUnderlineLengthMustMatchTitleLengthTest.php
Labels: New rule 🎁

#1341 Add tests for `NoPhpOpenTagInCodeBlockPhpDirective` rule
  src/Rule/NoPhpOpenTagInCodeBlockPhpDirective.php
  tests/Rule/NoPhpOpenTagInCodeBlockPhpDirectiveTest.php
Labels: bug

#1342 Add tests for `PhpOpenTagInCodeBlockPhpDirective` rule
  src/Rule/PhpOpenTagInCodeBlockPhpDirective.php
  tests/Rule/PhpOpenTagInCodeBlockPhpDirectiveTest.php
Labels: bug

#1362 Replace annotation by attribute
  composer.json
  composer.lock
  config/services.php
  docs/rules.md
  src/Attribute/Rule/Description.php
  src/Attribute/Rule/InvalidExample.php
  src/Attribute/Rule/ValidExample.php
  src/Command/RulesCommand.php
  src/Rule/AmericanEnglish.php
  src/Rule/ArgumentVariableMustMatchType.php
  src/Rule/AvoidRepetetiveWords.php
  src/Rule/BeKindToNewcomers.php
  src/Rule/BlankLineAfterAnchor.php
  src/Rule/BlankLineAfterColon.php
  src/Rule/BlankLineAfterDirective.php
  src/Rule/BlankLineAfterFilepathInCodeBlock.php
  src/Rule/BlankLineAfterFilepathInPhpCodeBlock.php
  src/Rule/BlankLineAfterFilepathInTwigCodeBlock.php
  src/Rule/BlankLineAfterFilepathInXmlCodeBlock.php
  src/Rule/BlankLineAfterFilepathInYamlCodeBlock.php
  src/Rule/BlankLineBeforeDirective.php
  src/Rule/ComposerDevOptionAtTheEnd.php
  src/Rule/ComposerDevOptionNotAtTheEnd.php
  src/Rule/DeprecatedDirectiveShouldHaveVersion.php
  src/Rule/EnsureBashPromptBeforeComposerCommand.php
  src/Rule/EnsureExactlyOneSpaceBeforeDirectiveType.php
  src/Rule/EnsureExactlyOneSpaceBetweenLinkDefinitionAndLink.php
  src/Rule/EnsureLinkDefinitionContainsValidUrl.php
  src/Rule/ExtendAbstractAdmin.php
  src/Rule/ExtendAbstractController.php
  src/Rule/ExtendController.php
  src/Rule/ExtensionXlfInsteadOfXliff.php
  src/Rule/FilenameUsesDashesOnly.php
  src/Rule/FilenameUsesUnderscoresOnly.php
  src/Rule/MaxColons.php
  src/Rule/NoBashPrompt.php
  src/Rule/NoBracketsInMethodDirective.php
  src/Rule/NoContraction.php
  src/Rule/NoDirectiveAfterShorthand.php
  src/Rule/NoMergeConflict.php
  src/Rule/NoPhpPrefixBeforeBinConsole.php
  src/Rule/OnlyBackslashesInNamespaceInPhpCodeBlock.php
  src/Rule/OnlyBackslashesInUseStatementsInPhpCodeBlock.php
  src/Rule/PhpPrefixBeforeBinConsole.php
  src/Rule/ReplaceCodeBlockTypes.php
  src/Rule/SpaceBetweenLabelAndLinkInDoc.php
  src/Rule/SpaceBetweenLabelAndLinkInRef.php
  src/Rule/Typo.php
  src/Rule/UnusedLinks.php
  src/Rule/ValidInlineHighlightedNamespaces.php
  src/Rule/VersionaddedDirectiveShouldHaveVersion.php
  src/Rule/YamlInsteadOfYmlSuffix.php
  src/Rule/YarnDevOptionAtTheEnd.php
  src/Rule/YarnDevOptionNotAtTheEnd.php
  tests/Rule/StringReplacementTest.php
Labels: enhancement

#1360 Add `ForbiddenDirectives` rule
  src/Rule/ForbiddenDirectives.php
  tests/Rule/ForbiddenDirectivesTest.php
Labels: New rule 🎁
