Repository OskarStark/doctor-rst, pull requests merged in 2023-02, with the labels that each got.

#1276 Enhancement: New rule `NoMergeConflict`
  docs/rules.md
  src/Rule/NoMergeConflict.php
  tests/Rule/NoMergeConflictTest.php
Labels: New rule 🎁

#803 Don't consider RST comments as directives
  tests/Rule/BlankLineAfterDirectiveTest.php
Labels: bug

#1307 Enhancement: New rule `EnsureBashPromptBeforeComposerCommand`
  docs/rules.md
  src/Rule/EnsureBashPromptBeforeComposerCommand.php
  src/Traits/DirectiveTrait.php
  tests/Rule/EnsureBashPromptBeforeComposerCommandTest.php
  tests/Traits/DirectiveTraitTest.php
  tests/Util/DirectiveTraitWrapper.php
Labels: New rule 🎁

#1312 Enhancement: Use `DirectiveContent`
  src/Traits/DirectiveTrait.php
  tests/Traits/DirectiveTraitTest.php
Labels: enhancement

#1308 Fix: `EnsureBashPromptBeforeComposerCommand`
  src/Rule/EnsureBashPromptBeforeComposerCommand.php
  tests/Rule/EnsureBashPromptBeforeComposerCommandTest.php
Labels: bug
